### ISSUE TITLE
Svelte :global() modifier for css break css syntax

### ISSUE THREAD

**Issue by stalkerg** [UnwrittenFun/svelte-vscode#15]
Subj.  for example:
```css
.my-table :global(tr.create td button) {
    opacity: 0;
    transition: opacity 0.3s;
}
```
