### ISSUE TITLE
UnhandledPromiseRejectionWarning for SCSS via svelte-preprocess

### ISSUE THREAD

**Issue by khorpy** [UnwrittenFun/svelte-vscode#61]
I set up everything according to https://github.com/kaisermann/svelte-preprocess#with-svelte-vs-code and added node binary path to the config. Now I'm getting the following output for the Svelte in the VS Code (I've added an undefined variable to test compiler/linter):

```
Using Svelte v3.6.4 from c:\project\node_modules\svelte\compiler
(node:6788) UnhandledPromiseRejectionWarning: Error: Undefined variable: "$test".
    at options.error (c:\project\node_modules\node-sass\lib\index.js:291:26)
(node:6788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
```

This is a SASS excerpt I'm testing against:

```scss
<style lang="scss">
  @import "../../styles/vars.scss";

  ul {
    margin-left: 1em;
  }
  span {
    color: $test;
    cursor: pointer;
    &.current {
      color: lighten($light-background, 65%);
      font-weight: bolder;
    }
  }
</style>
```
